grid_search:
 class: GridSearchCV
 module: sklearn.model_selection
 params: 
  cv: 3
  verbose: 3
model_selection:
 module_0: 
  class: KNeighborsClassifier
  module: sklearn.neighbors
  params: 
   algorithm: kd_tree
   weights: uniform
   n_neighbors: 3
  search_param_gird: 
   algorithm: 
   - auto
   - ball_tree
   - kd_tree
   - brute
   weights:
   - uniform
   - distance
   n_neighbors:
   - 3
   - 5
    -9


 module_1:
  class: RandomForesClassifier
  module: sklearn.ensemble
  params:
   max_depth: 10
   max_features: sqrt
   n_estimatore: 3
  search_param_grid:
   max_depth:
   - 10
   - 15
   - 20
   max_features:
   - sqrt
   - log2
   n_estimatores:
   - 3
   - 5
   - 9

